"""Add composite indexes for entity queries

Revision ID: f32928f1d25f
Revises: y1234567913
Create Date: 2025-12-20 13:52:34.079963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f32928f1d25f'
down_revision: Union[str, None] = 'y1234567913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uk_entity_cleanup')
    op.alter_column('categories', 'languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_comment="Language codes (ISO 639-1) for this category, e.g. ['de', 'en']",
               existing_nullable=False)
    op.alter_column('categories', 'extraction_handler',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               comment="Handler for processing extractions: 'default' or 'event'",
               existing_nullable=False)
    op.alter_column('categories', 'created_by_id',
               existing_type=sa.UUID(),
               comment='User who created this category',
               existing_nullable=True)
    op.alter_column('categories', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='If true, visible to all users. If false, only visible to owner.',
               existing_nullable=False)
    op.alter_column('data_source_categories', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_dsc_category'), table_name='data_source_categories')
    op.drop_index(op.f('idx_dsc_data_source'), table_name='data_source_categories')
    op.alter_column('data_sources', 'category_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Legacy primary category - use categories relationship for N:M')
    op.alter_column('data_sources', 'entity_id',
               existing_type=sa.UUID(),
               comment='FK to entity (municipality/person/organization/event)',
               existing_nullable=True)
    op.alter_column('data_sources', 'location_id',
               existing_type=sa.UUID(),
               comment='FK to location for geographic clustering',
               existing_comment='FK to location (municipality/city/town)',
               existing_nullable=True)
    op.drop_constraint(op.f('fk_data_sources_category_id_categories'), 'data_sources', type_='foreignkey')
    op.create_foreign_key(op.f('fk_data_sources_category_id_categories'), 'data_sources', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_documents_category_status_discovered'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_discovered'), table_name='documents')
    op.drop_index(op.f('ix_documents_source_status'), table_name='documents')
    op.drop_constraint(op.f('uq_document_source_category_hash'), 'documents', type_='unique')
    op.create_unique_constraint('uq_document_source_hash', 'documents', ['source_id', 'file_hash'])
    op.alter_column('entities', 'created_by_id',
               existing_type=sa.UUID(),
               comment='User who created this entity',
               existing_nullable=True)
    op.alter_column('entities', 'owner_id',
               existing_type=sa.UUID(),
               comment='User who owns/is responsible for this entity',
               existing_nullable=True)
    op.drop_index(op.f('ix_entities_country_admin_levels'), table_name='entities')
    op.drop_index(op.f('ix_entities_type_active_name'), table_name='entities')
    op.create_index('ix_entities_admin1_admin2', 'entities', ['admin_level_1', 'admin_level_2'], unique=False)
    op.create_index('ix_entities_country_admin1', 'entities', ['country', 'admin_level_1'], unique=False)
    op.create_index('ix_entities_owner_active', 'entities', ['owner_id', 'is_active'], unique=False)
    op.create_index('ix_entities_type_active', 'entities', ['entity_type_id', 'is_active'], unique=False)
    op.create_index('ix_entities_type_name_normalized', 'entities', ['entity_type_id', 'name_normalized'], unique=False)
    op.drop_index(op.f('ix_entity_relations_source_type'), table_name='entity_relations')
    op.create_index('ix_entity_relations_source_active', 'entity_relations', ['source_entity_id', 'is_active'], unique=False)
    op.create_index('ix_entity_relations_target_active', 'entity_relations', ['target_entity_id', 'is_active'], unique=False)
    op.create_index('ix_entity_relations_type_active', 'entity_relations', ['relation_type_id', 'is_active'], unique=False)
    op.alter_column('entity_types', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='If true, visible to all users. If false, only visible to owner.',
               existing_nullable=False)
    op.drop_index(op.f('ix_extracted_data_category_confidence'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_document_category'), table_name='extracted_data')
    op.alter_column('facet_values', 'source_type',
               existing_type=postgresql.ENUM('DOCUMENT', 'MANUAL', 'PYSIS', 'SMART_QUERY', 'AI_ASSISTANT', 'IMPORT', name='facetvaluesourcetype'),
               server_default=None,
               comment='How this value was created (document, manual, pysis, etc.)',
               existing_comment='How this value was created (DOCUMENT, MANUAL, PYSIS, etc.)',
               existing_nullable=False)
    op.drop_index(op.f('ix_facet_values_entity_date_active'), table_name='facet_values', postgresql_where='((is_active = true) AND (event_date IS NOT NULL))')
    op.drop_index(op.f('ix_facet_values_entity_type_active'), table_name='facet_values', postgresql_where='(is_active = true)')
    op.drop_index(op.f('ix_facet_values_search_vector'), table_name='facet_values', postgresql_using='gin')
    op.create_index('ix_facet_values_entity_active', 'facet_values', ['entity_id', 'is_active'], unique=False)
    op.create_index('ix_facet_values_entity_event_date', 'facet_values', ['entity_id', 'event_date'], unique=False)
    op.create_index('ix_facet_values_entity_type', 'facet_values', ['entity_id', 'facet_type_id'], unique=False)
    op.create_foreign_key(op.f('fk_pysis_field_history_field_id_pysis_process_fields'), 'pysis_field_history', 'pysis_process_fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_pysis_processes_location_id'), table_name='pysis_processes')
    op.drop_index(op.f('ix_pysis_processes_location_name'), table_name='pysis_processes')
    op.drop_constraint(op.f('uq_location_pysis_process'), 'pysis_processes', type_='unique')
    op.drop_constraint(op.f('fk_pysis_processes_location_id_locations'), 'pysis_processes', type_='foreignkey')
    op.drop_column('pysis_processes', 'location_id')
    op.drop_column('pysis_processes', 'location_name')
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notifications_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text("'de'::character varying"),
               existing_nullable=False)
    op.add_column('pysis_processes', sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Location name for string matching'))
    op.add_column('pysis_processes', sa.Column('location_id', sa.UUID(), autoincrement=False, nullable=True, comment='FK to location'))
    op.create_foreign_key(op.f('fk_pysis_processes_location_id_locations'), 'pysis_processes', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_location_pysis_process'), 'pysis_processes', ['location_name', 'pysis_process_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pysis_processes_location_name'), 'pysis_processes', ['location_name'], unique=False)
    op.create_index(op.f('ix_pysis_processes_location_id'), 'pysis_processes', ['location_id'], unique=False)
    op.drop_constraint(op.f('fk_pysis_field_history_field_id_pysis_process_fields'), 'pysis_field_history', type_='foreignkey')
    op.drop_index('ix_facet_values_entity_type', table_name='facet_values')
    op.drop_index('ix_facet_values_entity_event_date', table_name='facet_values')
    op.drop_index('ix_facet_values_entity_active', table_name='facet_values')
    op.create_index(op.f('ix_facet_values_search_vector'), 'facet_values', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_facet_values_entity_type_active'), 'facet_values', ['entity_id', 'facet_type_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('ix_facet_values_entity_date_active'), 'facet_values', ['entity_id', 'event_date', 'is_active'], unique=False, postgresql_where='((is_active = true) AND (event_date IS NOT NULL))')
    op.alter_column('facet_values', 'source_type',
               existing_type=postgresql.ENUM('DOCUMENT', 'MANUAL', 'PYSIS', 'SMART_QUERY', 'AI_ASSISTANT', 'IMPORT', name='facetvaluesourcetype'),
               server_default=sa.text("'DOCUMENT'::facetvaluesourcetype"),
               comment='How this value was created (DOCUMENT, MANUAL, PYSIS, etc.)',
               existing_comment='How this value was created (document, manual, pysis, etc.)',
               existing_nullable=False)
    op.create_index(op.f('ix_extracted_data_document_category'), 'extracted_data', ['document_id', 'category_id'], unique=False)
    op.create_index(op.f('ix_extracted_data_category_confidence'), 'extracted_data', ['category_id', 'confidence_score'], unique=False)
    op.alter_column('entity_types', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='If true, visible to all users. If false, only visible to owner.',
               existing_nullable=False)
    op.drop_index('ix_entity_relations_type_active', table_name='entity_relations')
    op.drop_index('ix_entity_relations_target_active', table_name='entity_relations')
    op.drop_index('ix_entity_relations_source_active', table_name='entity_relations')
    op.create_index(op.f('ix_entity_relations_source_type'), 'entity_relations', ['source_entity_id', 'relation_type_id'], unique=False)
    op.drop_index('ix_entities_type_name_normalized', table_name='entities')
    op.drop_index('ix_entities_type_active', table_name='entities')
    op.drop_index('ix_entities_owner_active', table_name='entities')
    op.drop_index('ix_entities_country_admin1', table_name='entities')
    op.drop_index('ix_entities_admin1_admin2', table_name='entities')
    op.create_index(op.f('ix_entities_type_active_name'), 'entities', ['entity_type_id', 'is_active', 'name_normalized'], unique=False)
    op.create_index(op.f('ix_entities_country_admin_levels'), 'entities', ['country', 'admin_level_1', 'admin_level_2'], unique=False)
    op.alter_column('entities', 'owner_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who owns/is responsible for this entity',
               existing_nullable=True)
    op.alter_column('entities', 'created_by_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created this entity',
               existing_nullable=True)
    op.drop_constraint('uq_document_source_hash', 'documents', type_='unique')
    op.create_unique_constraint(op.f('uq_document_source_category_hash'), 'documents', ['source_id', 'category_id', 'file_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_documents_source_status'), 'documents', ['source_id', 'processing_status'], unique=False)
    op.create_index(op.f('ix_documents_source_discovered'), 'documents', ['source_id', 'discovered_at'], unique=False)
    op.create_index(op.f('ix_documents_category_status_discovered'), 'documents', ['category_id', 'processing_status', 'discovered_at'], unique=False)
    op.drop_constraint(op.f('fk_data_sources_category_id_categories'), 'data_sources', type_='foreignkey')
    op.create_foreign_key(op.f('fk_data_sources_category_id_categories'), 'data_sources', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('data_sources', 'location_id',
               existing_type=sa.UUID(),
               comment='FK to location (municipality/city/town)',
               existing_comment='FK to location for geographic clustering',
               existing_nullable=True)
    op.alter_column('data_sources', 'entity_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to entity (municipality/person/organization/event)',
               existing_nullable=True)
    op.alter_column('data_sources', 'category_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment=None,
               existing_comment='Legacy primary category - use categories relationship for N:M')
    op.create_index(op.f('idx_dsc_data_source'), 'data_source_categories', ['data_source_id'], unique=False)
    op.create_index(op.f('idx_dsc_category'), 'data_source_categories', ['category_id'], unique=False)
    op.alter_column('data_source_categories', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('categories', 'is_public',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_comment='If true, visible to all users. If false, only visible to owner.',
               existing_nullable=False)
    op.alter_column('categories', 'created_by_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created this category',
               existing_nullable=True)
    op.alter_column('categories', 'extraction_handler',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'default'::character varying"),
               comment=None,
               existing_comment="Handler for processing extractions: 'default' or 'event'",
               existing_nullable=False)
    op.alter_column('categories', 'languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text('\'["de"]\'::jsonb'),
               existing_comment="Language codes (ISO 639-1) for this category, e.g. ['de', 'en']",
               existing_nullable=False)
    op.create_table('uk_entity_cleanup',
    sa.Column('duplicate_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('canonical_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('dup_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('can_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
