"""Pydantic Schemas for API request/response validation."""

from app.schemas.analysis_template import (
    AggregationConfig,
    AnalysisTemplateCreate,
    AnalysisTemplateListResponse,
    AnalysisTemplateResponse,
    AnalysisTemplateUpdate,
    DisplayConfig,
    FacetConfig,
)

# API Configuration (unified external API management)
from app.schemas.api_configuration import (
    APIConfigurationBase,
    APIConfigurationCreate,
    APIConfigurationDetail,
    APIConfigurationListResponse,
    APIConfigurationResponse,
    APIConfigurationUpdate,
    SyncRecordBase,
    SyncRecordDetail,
    SyncRecordListResponse,
    SyncRecordResponse,
    SyncStatsResponse,
    TestConnectionResponse,
    TriggerSyncRequest,
    TriggerSyncResponse,
)
from app.schemas.assistant import (
    SLASH_COMMANDS,
    ActionChange,
    ActionDetails,
    ActionExecuteRequest,
    ActionExecuteResponse,
    ActionPreviewResponse,
    AssistantChatRequest,
    AssistantChatResponse,
    AssistantContext,
    AssistantResponseData,
    ConversationMessage,
    HelpResponse,
    IntentType,
    NavigationResponse,
    QueryResponse,
    RedirectResponse,
    SlashCommand,
    SuggestedAction,
    ViewMode,
)
from app.schemas.category import (
    CategoryCreate,
    CategoryListResponse,
    CategoryResponse,
    CategoryUpdate,
)
from app.schemas.common import (
    ErrorResponse,
    MessageResponse,
    PaginatedResponse,
    PaginationParams,
)
from app.schemas.crawl_job import (
    CrawlJobCreate,
    CrawlJobListResponse,
    CrawlJobResponse,
    CrawlJobStats,
)
from app.schemas.custom_summary import (
    SCHEDULE_PRESETS as SUMMARY_SCHEDULE_PRESETS,
)

# Custom Summaries
from app.schemas.custom_summary import (
    ExecutionStatus,
    SharedSummaryAccessRequest,
    SharedSummaryResponse,
    SummaryCreate,
    SummaryCreateFromPrompt,
    SummaryDetailResponse,
    SummaryExecuteRequest,
    SummaryExecuteResponse,
    SummaryExecutionDetailResponse,
    SummaryExecutionResponse,
    SummaryFavoriteToggleResponse,
    SummaryFromPromptResponse,
    SummaryListResponse,
    SummaryResponse,
    SummarySchedulePreset,
    SummaryShareCreate,
    SummaryShareResponse,
    SummaryStatus,
    SummaryTriggerType,
    SummaryUpdate,
    SummaryWidgetCreate,
    SummaryWidgetResponse,
    SummaryWidgetType,
    SummaryWidgetUpdate,
    WidgetPosition,
    WidgetQueryConfig,
    WidgetVisualizationConfig,
)
from app.schemas.data_source import (
    DataSourceBulkImport,
    DataSourceCreate,
    DataSourceListResponse,
    DataSourceResponse,
    DataSourceUpdate,
)
from app.schemas.document import (
    DocumentListResponse,
    DocumentResponse,
    DocumentSearchParams,
)
from app.schemas.entity import (
    EntityBrief,
    EntityCreate,
    EntityHierarchy,
    EntityListResponse,
    EntityResponse,
    EntityUpdate,
)

# New Entity-Facet System
from app.schemas.entity_type import (
    EntityTypeCreate,
    EntityTypeListResponse,
    EntityTypeResponse,
    EntityTypeUpdate,
)
from app.schemas.extracted_data import (
    ExtractedDataResponse,
    ExtractedDataUpdate,
    ExtractedDataVerify,
)
from app.schemas.facet_type import (
    FacetTypeCreate,
    FacetTypeListResponse,
    FacetTypeResponse,
    FacetTypeUpdate,
)
from app.schemas.facet_value import (
    EntityFacetsSummary,
    FacetValueAggregated,
    FacetValueCreate,
    FacetValueListResponse,
    FacetValueResponse,
    FacetValueUpdate,
)
from app.schemas.location import (
    AdminLevelInfo,
    AdminLevelsResponse,
    CountryInfo,
    LocationCreate,
    LocationListResponse,
    LocationResponse,
    LocationSearchResponse,
    LocationSearchResult,
    LocationUpdate,
)
from app.schemas.relation import (
    EntityRelationCreate,
    EntityRelationListResponse,
    EntityRelationResponse,
    EntityRelationsGraph,
    EntityRelationUpdate,
    RelationTypeCreate,
    RelationTypeListResponse,
    RelationTypeResponse,
    RelationTypeUpdate,
)

__all__ = [
    # Category
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "CategoryListResponse",
    # DataSource
    "DataSourceCreate",
    "DataSourceUpdate",
    "DataSourceResponse",
    "DataSourceListResponse",
    "DataSourceBulkImport",
    # CrawlJob
    "CrawlJobCreate",
    "CrawlJobResponse",
    "CrawlJobListResponse",
    "CrawlJobStats",
    # Document
    "DocumentResponse",
    "DocumentListResponse",
    "DocumentSearchParams",
    # ExtractedData
    "ExtractedDataResponse",
    "ExtractedDataUpdate",
    "ExtractedDataVerify",
    # Common
    "PaginationParams",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    # Location (legacy)
    "LocationCreate",
    "LocationUpdate",
    "LocationResponse",
    "LocationListResponse",
    "LocationSearchResult",
    "LocationSearchResponse",
    "CountryInfo",
    "AdminLevelInfo",
    "AdminLevelsResponse",
    # Entity-Facet System - EntityType
    "EntityTypeCreate",
    "EntityTypeUpdate",
    "EntityTypeResponse",
    "EntityTypeListResponse",
    # Entity-Facet System - Entity
    "EntityCreate",
    "EntityUpdate",
    "EntityResponse",
    "EntityListResponse",
    "EntityBrief",
    "EntityHierarchy",
    # Entity-Facet System - FacetType
    "FacetTypeCreate",
    "FacetTypeUpdate",
    "FacetTypeResponse",
    "FacetTypeListResponse",
    # Entity-Facet System - FacetValue
    "FacetValueCreate",
    "FacetValueUpdate",
    "FacetValueResponse",
    "FacetValueListResponse",
    "FacetValueAggregated",
    "EntityFacetsSummary",
    # Entity-Facet System - Relations
    "RelationTypeCreate",
    "RelationTypeUpdate",
    "RelationTypeResponse",
    "RelationTypeListResponse",
    "EntityRelationCreate",
    "EntityRelationUpdate",
    "EntityRelationResponse",
    "EntityRelationListResponse",
    "EntityRelationsGraph",
    # Entity-Facet System - AnalysisTemplate
    "AnalysisTemplateCreate",
    "AnalysisTemplateUpdate",
    "AnalysisTemplateResponse",
    "AnalysisTemplateListResponse",
    "FacetConfig",
    "AggregationConfig",
    "DisplayConfig",
    # Assistant
    "AssistantContext",
    "AssistantChatRequest",
    "AssistantChatResponse",
    "AssistantResponseData",
    "ConversationMessage",
    "IntentType",
    "ViewMode",
    "QueryResponse",
    "ActionPreviewResponse",
    "NavigationResponse",
    "RedirectResponse",
    "HelpResponse",
    "ActionDetails",
    "ActionChange",
    "ActionExecuteRequest",
    "ActionExecuteResponse",
    "SuggestedAction",
    "SlashCommand",
    "SLASH_COMMANDS",
    # Custom Summaries
    "SummaryStatus",
    "SummaryTriggerType",
    "SummaryWidgetType",
    "ExecutionStatus",
    "WidgetPosition",
    "WidgetQueryConfig",
    "WidgetVisualizationConfig",
    "SummaryWidgetCreate",
    "SummaryWidgetUpdate",
    "SummaryWidgetResponse",
    "SummaryExecutionResponse",
    "SummaryExecutionDetailResponse",
    "SummaryShareCreate",
    "SummaryShareResponse",
    "SharedSummaryAccessRequest",
    "SharedSummaryResponse",
    "SummaryCreateFromPrompt",
    "SummaryCreate",
    "SummaryUpdate",
    "SummaryResponse",
    "SummaryDetailResponse",
    "SummaryListResponse",
    "SummaryFromPromptResponse",
    "SummaryExecuteRequest",
    "SummaryExecuteResponse",
    "SummaryFavoriteToggleResponse",
    "SummarySchedulePreset",
    "SUMMARY_SCHEDULE_PRESETS",
    # API Configuration
    "APIConfigurationBase",
    "APIConfigurationCreate",
    "APIConfigurationUpdate",
    "APIConfigurationResponse",
    "APIConfigurationDetail",
    "APIConfigurationListResponse",
    "SyncRecordBase",
    "SyncRecordResponse",
    "SyncRecordDetail",
    "SyncRecordListResponse",
    "TriggerSyncRequest",
    "TriggerSyncResponse",
    "TestConnectionResponse",
    "SyncStatsResponse",
]
